// `sivru help` — print the CLI usage banner.
//
// Output is plain text by design: agents grep this; humans read it. Color and
// styling per DESIGN.md §6.10 land in a later pass. Keep this file in sync
// when commands are added or removed in `./index.ts`.

const HELP_TEXT = [
  "sivru — code search + comprehension for coding agents",
  "",
  "Usage: sivru <command> [args]",
  "",
  "Commands:",
  "  search <query> [path]       Index path (default .) and print top-k matches",
  "  index <path>                Walk + chunk + index without searching, print stats",
  "  mcp                         Run as a stdio MCP server (used by Claude Code)",
  "  from-git <url>              Clone <url> at depth=1, cache, and index",
  "  session list                List Claude Code sessions in ~/.claude/projects/",
  "  session show <id-prefix>    Stream events for one session",
  "  observe                     Boot the local web UI + HTTP API (port 7676)",
  "  observe init                One-shot setup: register MCP + write CLAUDE.md + subagent file",
  "  observe replay <id-prefix>  Static counterfactual replay for one session",
  "  observe costs               Aggregate counterfactual rollup across sessions",
  "  doctor                      Preflight + diagnostic checks",
  "  bench personal              Benchmark sivru on YOUR sessions + repos (multi-model sweep)",
  "  bench models                List registered embedding models with size/RAM/license info",
  "  config get|set|unset|list   Manage persistent CLI settings (e.g. default embedder)",
  "  skill install|uninstall     Install/remove the Claude Code routing skill",
  "  explain <path>              Public API, callers, callees, churn & ownership for one file",
  "  explain --project           Project the whole repo into the System→Module→Package→Symbol model",
  "  explain --html              Render the project model as one self-contained, offline HTML map",
  "  feedback apply <patch.json> Write an explainer patch back to @sivru blocks / .sivru/explainer.md",
  "  checkup                     Coach-loop: report drift in CLAUDE.md / SKILL.md / agent files",
  "  block validate [path]       Lint every @sivru annotation block under path (default cwd)",
  "  block extract [path]        Emit every block + diagnostics (use with --json)",
  "  block staleness [path]      Flag blocks whose source changed since they were authored",
  "  block graph [path]          Cross-block reference graph (--check fails on a broken edge)",
  "  block check-enforcement     Verify invariant→test linkage (E230/E231/E232)",
  "  block init <path::symbol>   Scaffold a starter @sivru block for a symbol",
  "  version                     Print the version",
  "  help                        Print this help",
  "",
  "search options:",
  "  --top=N                     Number of results (default 10)",
  "  --bm25                      BM25-only (faster cold start, no model download).",
  "                              Default mode is hybrid (BM25 + semantic cosine,",
  "                              RRF-merged) — first run downloads ~25 MB to",
  "                              ~/.cache/sivru/models/.",
  "  --hybrid                    Explicit hybrid (default — kept for back-compat).",
  "  --json                      Emit results as a JSON array on a single line",
  "",
  "index options:",
  "  --json                      Emit stats as a JSON object on a single line",
  "",
  "from-git options:",
  "  -r, --ref <ref>             Branch / tag / commit to check out (default HEAD)",
  "  --allow-private-urls        Skip the SSRF guard (private IPs / localhost)",
  "  --json                      Emit a JSON object on a single line",
  "",
  "session options:",
  "  --all                       (list) Include older sessions beyond the default 20",
  "  --json                      Emit JSON instead of a text table",
  "  --limit=N                   (show) Cap events streamed (default: no cap)",
  "  --projects-root <dir>       Override ~/.claude/projects/ (used by tests)",
  "",
  "observe options:",
  "  -p, --port <port>           Server port (default 7676)",
  "  --host <host>               Listen host (default 127.0.0.1)",
  "  --no-ui                     Skip mounting the observe-ui dist",
  "  --json                      (replay/costs) Emit JSON instead of text",
  "  --since=N                   (costs) Only include sessions updated in last N days",
  "  --projects-root <dir>       (replay/costs) Override ~/.claude/projects/",
  "  --dry-run                   (init) Show changes without writing",
  "  --skip-mcp / --skip-claude-md / --skip-subagent  (init) Disable individual steps",
  "  --cwd <dir>                 (init) Override the project directory",
  "  --writable                  (mcp, via observe API) Enable the block/feedback write tools",
  "",
  "doctor options:",
  "  --json                      Emit a structured JSON report",
  "",
  "bench personal options:",
  "  --models <list>             Comma-separated short names: bm25, potion, minilm, bge-small,",
  "                              or hf:<owner/model> for arbitrary HF feature-extraction model",
  "                              (default: bm25,potion)",
  "  --n=N                       Max queries per repo (default 10)",
  "  --since=N                   Only include sessions in the last N days",
  "  --repo <path>               Restrict to one repo (otherwise auto-discover)",
  "  --json                      Emit a structured JSON report",
  "",
  "skill options:",
  "  --project                   Install into <git repo root>/.claude/skills/",
  "                              instead of the default ~/.claude/skills/",
  "  --force                     Overwrite even a non-sivru file at the path",
  "  --cwd <dir>                  Directory --project resolves the git root from",
  "",
  "explain options:",
  "  <path>                      Repo-relative file, or path::symbol for a region",
  "  --project                   Whole-repo projection (System→Module→Package→Symbol); no <path>",
  "  --html                      Render the projection as one self-contained HTML file (implies --project)",
  "  --out=<path>                Output path for --html (default ./sivru-explainer.html)",
  "  --diff                      Scope a file/region explain to what changed",
  "  --json                      Emit the canonical ExplainArtifact / model JSON",
  "  --since=<N>                 Churn window in days (default 90)",
  "  --depth=<N>                 Call-graph depth (v0.5: only 1)",
  "  --repo=<dir>                Repo root to resolve <path> against (default cwd)",
  "",
  "feedback apply options:",
  "  --dry-run                   Show the per-block before/after; write nothing",
  "  --force                     Apply even to files with uncommitted changes",
  "  --repo=<dir>                Repo root (default: the patch's repoRoot, else cwd)",
  "",
  "block options:",
  "  --json                      (extract) Emit every block + diagnostics as JSON",
  "                              (validate exits non-zero on any error-level diagnostic)",
  "  --autofix                   (validate) Rewrite the auto-fixable diagnostics in place",
  "  --check                     (graph) Exit non-zero on a broken cross-block edge",
  "  --changed-since=<ref>       (staleness) Compare against a git ref",
  "",
  "Tracked at https://github.com/sivru/sivru",
].join("\n");

export async function runHelp(_argv: readonly string[]): Promise<number> {
  process.stdout.write(HELP_TEXT + "\n");
  return 0;
}
